apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: maxprime
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          # containerConcurrency: 1
          container:
            # image: gcr.io/s9-demo/maxprime:latest
            image: gcr.io/knative-samples/maxprime
            env:
            - name: RELEASE
              value: "v0.0.1-manual"
            - name: GIN_MODE
              value: "release"